language: go
warnings_are_errors: false

go:
        - 1.7
before_install:
        - git clone git://github.com/jedisct1/libsodium.git
        - ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
        - git clone git://github.com/zeromq/libzmq.git
        - ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
        - git clone git://github.com/zeromq/czmq.git
        - ( cd czmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
script:
        - go get -t -v ./...
        - go test -v .
